development: &defaults
  sessions:
    default: &default_session
      database: app
      hosts:
        - localhost:27017
  options:
    allow_dynamic_fields: false
    preload_models: true
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true